name: osh_safety_app
description: OSH Safety Management and AI Analysis Platform.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  fl_chart: ^0.63.0
  image_picker: ^1.0.4
  http: ^1.1.0
  flutter_stripe: ^9.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
